import {app, BrowserWindow, Menu} from 'electron';
import log from 'electron-log/main'
import {Launcher} from "./launcher";
import * as path from "node:path";

function getIconPath() {
    if (app.isPackaged) {
        return path.join(process.resourcesPath, "icons", "icon.png");
    }

    return path.join(__dirname, "../../resources/icons/icon.png");
}

// Initialize logger
log.initialize();

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
const launcher = new Launcher(!app.isPackaged);

const createWindow = async () => {
    const mainWindow = new BrowserWindow({
        height: 600,
        width: 800,
        icon: getIconPath(),
        title: "Multiroom",
        titleBarOverlay: {
            color: "#fff",
        }
    });

    Menu.setApplicationMenu(null);
    mainWindow.setIcon(getIconPath());
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    mainWindow.on("page-title-updated", (event) => {
        event.preventDefault();
    });

    await launcher.start();
    launcher.on('ready', (port: number): void => {
        const url = `http://localhost:${port}/?electron=true`;
        log.info("Loading url: ", url)
        mainWindow.loadURL(url);
        mainWindow.setTitle("Multiroom");
        mainWindow.setIcon(getIconPath());
    })
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(async () => {
    createWindow();
})
// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
app.on('before-quit', (event) => {
    event.preventDefault();
    launcher.stop().finally(() => {
        app.exit(0);
    })
})


// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit();
}
