name: CI

on:
  push:
    branches:
      - main
      - MUL-44
jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up GO
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: backend-go/go.sum

      - name: Build backend-go
        run: |
          pwd
          mkdir -p artifacts/bin/
          go build -C backend-go -o ../artifacts/bin/backend-go ./...

      - name: Confirm build
        run: |
          echo "Size of binary file:"
          ls -lh artifacts/bin/backend-go
          
          echo "File type:"
          file artifacts/bin/backend-go