name: CI

on:
  push:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: "Hello"
        run: echo "Runned!"
        
      - name: Смотрим на каком Ubuntu мы запущены
        run: lsb_release -a

      - name: Смотрим что уже установлено
        run: |
          echo "Go:    $(go version)"
          echo "Node:  $(node --version)"
          echo "CMake: $(cmake --version | head -1)"